atomics: Add support for targets without atomics
rust-lang/log pull request #413
Opened 2020-09-12 03:10 UTC by alistair23

Some targets (such as RV32IMC) don't have atomic support. This PR allows the log crate to build for those targets.

As the platform doesn't have atomics we can't implement an Atomic version of AtomicUsize, so this version is not atomic. Any platform without atomics is unlikely to have multiple cores, so this shouldn't be a problem.
    
This is somewhat based on implementations in: https://github.com/japaric/heapless

2020-09-18 16:31 UTC, alistair23 commented
Ping

2020-09-19 18:46 UTC, sfackler commented
This seems like a plausible approach, though I think we'll need to have CI target at least one of these architectures so the not(has_atomics) code doesn't rot.

2020-09-21 19:17 UTC, alistair23 commented
Done, I have added a CI test to build RISC-V without atomics.

2020-09-21 22:12 UTC, sfackler commented
Thanks!

cc @KodrAus does this seem okay to you as well? It's a bit scary, but it seems reasonable that a platform with no atomics can't really have threads either.

2020-09-21 22:34 UTC, dtolnay requested changes
I would like the rationale from the PR description to be documented on the unsafe impl.

```rust
// Any platform without atomics is unlikely to have multiple cores, so
// writing via Cell will not be a race condition.
```

2020-09-22 04:20 UTC, KodrAus commented on build.rs
> +    match &target[..] {
Maybe we could extract these into little functions so they're a bit easier to follow:

```rust
if target_has_atomic_cas { .. }

..

if target_has_atomics() { .. }
```

2020-09-22 04:25 UTC, KodrAus commented
I think I'd feel just a bit safer if we encapsulated the global logger code into a module, so that we limit the reachability of our "fake" `AtomicUsize` as much as possible, but I don't think that's a blocker.

2020-09-22 19:19 UTC, alistair23 commented
I think I have addressed all comments, let me know if there is anything else.

2020-09-22 23:38 UTC, merged

2020-09-22 23:38 UTC, sfackler commented
Thanks!

2020-09-23 00:04 UTC, alistair23 commented
Thanks for merging. Do you know when the next release will be?